export const s = {
  card: {
    background: "#ffffff",
    border: "1px solid #d4d2e0",
    borderTop: "3px solid #c6952e",
    borderRadius: 8,
    padding: 20,
    boxShadow: "0 2px 8px rgba(26,42,94,0.06)",
  },
  btnPrimary: {
    background: "linear-gradient(135deg, #1a2a5e, #2a3f7e)",
    color: "#e8d5a3",
    border: "none",
    borderRadius: 6,
    padding: "10px 20px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    boxShadow: "0 2px 8px rgba(26,42,94,0.25)",
    fontFamily: "'Sarabun', sans-serif",
  },
  btnGhost: {
    background: "#ffffff",
    border: "1px solid #d4d2e0",
    color: "#1a2a5e",
    borderRadius: 6,
    padding: "8px 16px",
    fontSize: 13,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontFamily: "'Sarabun', sans-serif",
  },
  input: {
    background: "#ffffff",
    border: "1px solid #d4d2e0",
    borderRadius: 6,
    color: "#1a1a2e",
    padding: "8px 12px",
    fontSize: 13,
    width: "100%",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "'Sarabun', sans-serif",
  },
  dashboardCard: {
    background: "#ffffff",
    border: "1px solid #d4d2e0",
    borderTop: "3px solid #c6952e",
    borderRadius: 8,
    padding: 16,
    cursor: "pointer",
    transition: "all .15s ease",
    boxShadow: "0 2px 8px rgba(26,42,94,0.06)",
  },
  insightPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 9,
    fontWeight: 600,
    borderRadius: 10,
    padding: "2px 8px",
    whiteSpace: "nowrap",
  },
};
